language: node_js
node_js:
  - "stable"

script:
  - yarn run dist

before_deploy:
  - mv ./dist ./aurial
  - tar -czf ./aurial.tgz ./aurial && mv ./aurial.tgz ./aurial/aurial.tgz

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./aurial/
  on:
    branch: master
